from __future__ import annotations

from typing import Any

import psycopg
from psycopg.rows import dict_row
from psycopg.types.json import Jsonb


class ApprovedCaseMemory:
    """PostgreSQL-backed case history; only an explicit approval path may write."""

    def __init__(self, database_url: str):
        self.database_url = database_url

    @staticmethod
    def _ensure_schema(connection: psycopg.Connection) -> None:
        connection.execute(
            """CREATE TABLE IF NOT EXISTS approved_case_memory (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                instance_id TEXT NOT NULL,
                request_id TEXT,
                approved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                approval_method TEXT NOT NULL,
                report JSONB NOT NULL
            )"""
        )
        connection.execute(
            "ALTER TABLE approved_case_memory ADD COLUMN IF NOT EXISTS request_id TEXT"
        )
        connection.execute(
            """CREATE INDEX IF NOT EXISTS idx_case_memory_instance_request_time
            ON approved_case_memory(instance_id, request_id, approved_at DESC)"""
        )

    def recent(self, instance_id: str, request_id: str, limit: int = 2) -> list[dict[str, Any]]:
        with psycopg.connect(self.database_url, row_factory=dict_row, connect_timeout=3) as connection:
            self._ensure_schema(connection)
            rows = connection.execute(
                """SELECT id, approved_at, approval_method, report
                FROM approved_case_memory
                WHERE instance_id = %s AND request_id = %s
                ORDER BY approved_at DESC, id DESC LIMIT %s""",
                (instance_id, request_id, min(max(int(limit), 1), 3)),
            ).fetchall()
        cases: list[dict[str, Any]] = []
        for row in rows:
            report = row["report"] if isinstance(row["report"], dict) else {}
            evidence = report.get("evidence", [])
            cases.append(
                {
                    "memory_id": row["id"],
                    "instance_id": instance_id,
                    "request_id": request_id,
                    "approved_at": row["approved_at"].isoformat(),
                    "approval_method": row["approval_method"],
                    "verdict": report.get("verdict"),
                    "summary": str(report.get("summary", ""))[:500],
                    "hypothesis": str(report.get("hypothesis", ""))[:500],
                    "evidence": evidence[:5] if isinstance(evidence, list) else [],
                }
            )
        return cases

    def save_approved(
        self, instance_id: str, request_id: str, report: dict[str, Any]
    ) -> dict[str, Any]:
        with psycopg.connect(self.database_url, row_factory=dict_row, connect_timeout=3) as connection:
            self._ensure_schema(connection)
            row = connection.execute(
                """INSERT INTO approved_case_memory(instance_id, request_id, approval_method, report)
                VALUES (%s, %s, %s, %s) RETURNING id, approved_at""",
                (instance_id, request_id, "explicit_flag", Jsonb(report)),
            ).fetchone()
        assert row is not None
        return {"memory_id": row["id"], "approved_at": row["approved_at"].isoformat()}
